runtime: python311 # Or python39, python310, python312. Match your development environment.
entrypoint: gunicorn -b :$PORT main:app # How GAE starts your app. -b :$PORT is important.

instance_class: F1 # Smallest instance class, good for free tier and light load.

automatic_scaling:
  min_instances: 0    # Allows scaling to zero to save costs when idle.
  max_instances: 2    # Start with a low number to control costs. Increase if needed.
  # target_cpu_utilization: 0.65 # Example: scale up if CPU usage is high.
  # min_pending_latency: 30ms    # Example: respond quickly to initial requests.
  # max_pending_latency: automatic
  # max_concurrent_requests: 80  # Default is 10 for F1, can be increased.

handlers:
# This handler serves static files (e.g., CSS, JS) if you create a 'static' folder.
# - url: /static
#   static_dir: static

# This handler routes all other requests to your Flask application.
- url: /.*
  script: auto
  secure: always # Enforce HTTPS

# You can set environment variables here if needed
# env_variables:
#   FLASK_SECRET_KEY: "your_production_secret_key_here_if_not_set_in_code_or_env"
#   # GAE automatically provides GOOGLE_CLOUD_PROJECT